import './globals.css';
import type { Metadata, Viewport } from 'next';
import type { ReactNode } from 'react';
import { Providers } from './providers';

export const metadata: Metadata = {
  title: 'Dynasty — economic strategy simulation',
  description:
    'A persistent, server-authoritative economic strategy game: trade commodities across a living world, build businesses, run production, manage crews, debt and risk.',
  applicationName: 'Dynasty',
  manifest: '/manifest.webmanifest',
  /*
   * The icons are generated by `npm run icons` (see `scripts/generate-icons.ts`) and are
   * regenerated on every production build by the `prebuild` script, so these paths always
   * resolve. Referencing a file that does not exist is worse than referencing none: an
   * install prompt that half-works looks broken.
   */
  icons: {
    icon: [
      { url: '/icons/generated/icon-192.png', sizes: '192x192', type: 'image/png' },
      { url: '/icons/generated/icon-512.png', sizes: '512x512', type: 'image/png' },
    ],
    apple: [{ url: '/icons/generated/icon-192.png', sizes: '192x192', type: 'image/png' }],
  },
  appleWebApp: { capable: true, title: 'Dynasty', statusBarStyle: 'black-translucent' },
  formatDetection: { telephone: false },
};

export const viewport: Viewport = {
  themeColor: '#05070d',
  width: 'device-width',
  initialScale: 1,
  viewportFit: 'cover',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className="min-h-screen antialiased">
        <a
          href="#main"
          className="sr-only focus:not-sr-only focus:absolute focus:top-2 focus:left-2 focus:z-[100] focus:rounded focus:bg-gold focus:px-3 focus:py-1.5 focus:text-sm focus:font-semibold focus:text-abyss"
        >
          Skip to content
        </a>
        <Providers>
          <div id="main">{children}</div>
        </Providers>
      </body>
    </html>
  );
}
